name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Buildozer deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            zlib1g-dev libncurses5 libstdc++6 libffi-dev \
            libssl-dev autoconf automake libtool \
            cmake pkg-config

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 Cython==0.29.36 virtualenv

      - name: Build debug APK
        env:
          BUILDOZER_WARN_ON_ROOT: "1"
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
