name: Build WeChat Ledger APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-8-jdk git zip unzip build-essential

    - name: Install Buildozer & deps
      run: |
        pip3 install --user buildozer cython
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache Buildozer downloads
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build APK (debug)
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: wechat-ledger-debug
        path: bin/*.apk
        retention-days: 30
